### ISSUE TITLE
Terncy在Home Assistant中每隔一两天就会断开连接

### ISSUE THREAD

**Issue by lzw103092** [rxwen/homeassistant-terncy-component#114]
小燕网关IP：已设置为静态IP
Home Assistant版本：2025.5.3
集成版本1.0.58

我在Home Assistant中使用Terncy集成时，发现控制大约每隔1-2天就会断开连接，导致所有Terncy设备变为不可用，无法控制。

系统日志里内容为
Logger: custom_components.terncy.core.gateway.192.168.8.164  
Source: custom_components/terncy/core/gateway.py:275  
Disconnected: box-1c-82-59-90-04-bb

此时只能通过重启Home Assistant，或者在设置中禁用后再启用该集成，才能恢复控制。

能否在集成中增加断线自动重连机制，或在检测到连接断开后自动尝试重新连接，而不需要人工干预或重启HA？

感谢您开发并维护这个集成，如需提供更多日志或信息我也可以进一步补充！

**Comment by caibinqing** [comment]
集成内部是有重连机制的，但看你描述好像是没能连回去。不禁用，只重载集成能恢复吗？

这种网络问题是挺难排查的，或许你可以收集一下DEBUG日志，看看有没有线索

```yaml
logger:
  default: warning
  logs:
    custom_components.terncy: debug
    terncy.terncy: debug
```

这里把底层库的debug也打开一起看
