### ISSUE TITLE
窗帘增加停止功能

### ISSUE THREAD

**Issue by wyz6123707** [rxwen/homeassistant-terncy-component#34]
如题，麻烦大佬给开合帘增加停止的功能吧，现在只有开、关、特定开启比例的功能，希望能够增加停止的功能。

**Comment by Necroneco** [comment]
可以在 `/config/configuration.yaml` 中加上这段，重启HA打开系统日志

```yaml
logger:
  default: warning
  logs:
    custom_components.terncy: debug
    terncy.terncy: debug
```
