### ISSUE TITLE
请问是否支持小燕人体存在传感器     TERNCY-PS01

### ISSUE THREAD

**Issue by latel** [rxwen/homeassistant-terncy-component#45]
<img width="639" alt="image" src="https://github.com/rxwen/homeassistant-terncy-component/assets/5621862/3641ad26-72b7-4400-b90c-da00ea88fda3">

**Comment by Necroneco** [comment]
接入看一下，如果没支持的话，请提供一下日志，

在 `/config/configuration.yaml` 中加入这段，然后重启HA

```yaml
logger:
  default: warning
  logs:
    custom_components.terncy: debug
```
