### ISSUE TITLE
开关的按键不可用

### ISSUE THREAD

**Issue by lifetimr** [rxwen/homeassistant-terncy-component#91]
core1.2中开关的按键次数无法作为触发条件，麻烦大佬看看啥问题吧？

**Comment by caibinqing** [comment]
嗯 确实存在问题，暂时先用 event 代替吧。

```yaml
triggers:
  - trigger: state
    entity_id:
      - event.****************_button
    not_from: unavailable
    not_to: unavailable
```
